# Generated by Django 6.0 on 2025-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="movies/")),
                ("duration", models.DurationField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
