# Generated by Django 6.0 on 2025-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="video",
            name="file_path",
        ),
        migrations.AddField(
            model_name="video",
            name="video_url",
            field=models.URLField(default="''"),
            preserve_default=False,
        ),
    ]
