# Generated by Django 4.2.7 on 2025-12-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_remove_video_duration_remove_video_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
