# Generated by Django 4.2.7 on 2025-12-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="room",
            field=models.CharField(default="general", max_length=50),
        ),
    ]
